### ISSUE TITLE
Petit freeze in REPL

### ISSUE THREAD

**Issue by masatoi** [Shinmera/portacle#25]
Petit freeze occurs when company-mode completion candidates pop-up in REPL.
This problem does not occur when company-quickhelp-mode is disabled or company-quickhelp-delay variable has bigger value such 1.0.

**Comment by Shinmera** [comment]
I'm not sure where I stand with this. I don't want to disable the quickhelp as it is very useful and a feature most modern IDEs sport. Increasing the delay makes it more surprising when the help pops up, and rather annoying because you often have to wait when you start typing and know you want to use the help. On the other hand, as you mention, it creates stuttering and performance problems.

**Comment by masatoi** [comment]
In my environment (Linux and Windows 7), it was OK that set the delay to 0.6. but 0.5 or less caused this freeze. Does it reproduce?

**Comment by Shinmera** [comment]
I think the freeze depends on how fast your machine is and how loaded your Lisp environment is with symbols / how many items there are as possible completions. As such there's no "perfect value" to set it to so that it never freezes.

**Comment by Shinmera** [comment]
I've increased the value a bit, but I doubt the issue will be solved completely because of the reasons described above.
