### ISSUE TITLE
Problems opening in macOS

### ISSUE THREAD

**Issue by nachoba** [Shinmera/portacle#43]
When I try to open portacle it does not open. However if I go to the contents of the package:
Portacle.app/Contents/MacOS/portacle
And run it: The application runs opening a terminal and showing this errors:
Warning: arch-dependent data dir '/Users/linus/portacle/mac/emacs/libexec/emacs/25.1/x86_64-apple-darwin16.5.0/': No such file or directory

Warning: Lisp directory '/Users/linus/portacle/mac/emacs/share/emacs/25.1/lisp': No such file or directory

Clearly my user is not "linus". Is there a file in which I can configure this?
Thanks

**Comment by nachoba** [comment]
Well I took a look at closed issues and seems that there is a fix for this.
I did the move the Portable.app to another directory and then put it back and now it works perfectly.
Sorry.

**Comment by Shinmera** [comment]
The website mentions this under the OS X installation issues. It's a bother, I know, but there's unfortunately no fix for it.

**Comment by brandelune** [comment]
Sorry to add on a closed issue:
1) the explanations for the OSX install should have "Preferences" instead of "Prefrences"
2) why the "" around "security" ?
3) no need to modify the preferences, just right click on the application and select open
4) Cmd+Q does not work → either call "Quit" from the menu or used C-x C-c...

**Comment by Shinmera** [comment]
The "security" is because having to move the app with finder is a really annoying contrivance that was introduced in 10.12 which does not actually provide much in terms of improved security at all, but instead punishes a lot of legitimate applications.

**Comment by brandelune** [comment]
There is no technical proof that Portacle is a "legitimate" application. Maybe you should give the technical reasons instead of writing "security".

**Comment by brandelune** [comment]
There are plenty of FLOSS packages that are not signed and that install and run without issue. If your package has special needs you should mention that clearly somewhere in the documentation.

What matters is that Portacle is supposed to be based on technologies that are easily installed and that run without any security issues. If your packaging method introduces issues then there is a problem with your packaging method, not with how OSX deals with "security". If you do not give information on why such issues occur then nobody will be able to help you with the packaging.

Also, the method you propose to circumvent the issue is not a standard one. Users should not have to fiddle with the System Preferences to run non-signed apps (especially those who are sufficiently technology aware that they want to run a CL environment). As I suggested, right-clicking on a non signed package and accepting to open it is usually sufficient and works in the case of Portacle.
