### ISSUE TITLE
Fails on linux ubuntu 14.04

### ISSUE THREAD

**Issue by stacksmith** [Shinmera/portacle#5]
clicking on .desktop file does not do anything (visible)
executing portacle.run fails:
`
xxx/portacle/emacs/lin/emacs.sh: line 46: xxx/portacle/emacs/lin/bin/emacs: No such file or directory`

(anonymizing my directory structure with xxx)

**Comment by Shinmera** [comment]
That is very peculiar. Does the file in question exist or not? Does your full path contain spaces or something similar?

**Comment by Shinmera** [comment]
Actually-- did you download the release archive `lin64-portacle.zip` or did you clone/download the sources? The latter case would explain the absence of the file. You'll have to build it yourself, since the repo only contains script and configuration files. See https://github.com/Shinmera/portacle/tree/master/build for build instructions.

**Comment by Shinmera** [comment]
Closing due to lack of response.
